# llm-banker-spark-pipeline/docker-compose.yml
version: '3.8'

services:
  spark_worker:
    build: .
    volumes:
      # 핵심 1: 옆 레포지토리(챗봇)의 logs 폴더를 읽어오기
      - ../llm-banker-rag-chatbot/logs:/app/logs
      
      # 핵심 2: 스파크 분석 결과물은 내 레포지토리의 output 폴더에 저장하기
      - ./output:/app/output